### PR TITLE
fix for venv override fact

### PR DESCRIPTION
**Pull request by g0rgamesh**
Set fact takes precedence over virtual environment variable in other roles:
`IDENTITY_API_VERSION=3 /usr/bin/python3 /home/stack/.ansible/tmp/ansible-tmp-1710852078.3961973-1188828-59557818542981/AnsiballZ_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/stack/.ansible/tmp/ansible-tmp-1710852078.3961973-1188828-59557818542981/ > /dev/null 2>&1 && sleep 0'`

### CODE REVIEW

**Review by markgoddard — CHANGES_REQUESTED** [review]
Could you change it to use the same pattern used in the other roles, e.g. os_flavors?

**Comment by g0rgamesh** [comment]
> Could you change it to use the same pattern used in the other roles, e.g. os_flavors?

Sure

**Review by markgoddard — APPROVED** [review]

**Comment by g0rgamesh** [comment]
We should make a new collection release, it's needed for customer CI.

**Comment by markgoddard** [comment]
> We should make a new collection release, it's needed for customer CI.

Done: https://github.com/stackhpc/ansible-collection-openstack/releases/tag/0.1.1

**Pull request merged**
